### ISSUE TITLE
RoadMap

### ISSUE THREAD

**Issue by kipkurui** [BioinfoNet/Affordabee#1]
Populate some of the tasks for the Sprint:

- [x] Understand [GitHub Actions](https://github.com/features/actions)
- [x] Create a prototype GitHub Page for _Affordabee_
- [x] Prepare our Introduction Document
